id int unsigned NOT NULL auto_increment,
  idobject int UNSIGNED NOT NULL default 0,
typeobject enum('post', 'image', 'comment') default 'post',
  best tinyint unsigned NOT NULL default '1',
  votes int UNSIGNED NOT NULL default 0,
  worstvotes int UNSIGNED NOT NULL default 0,
  bestvotes int UNSIGNED NOT NULL default 0,
  rate decimal(3,1) not null default '1.0',
  created datetime NOT NULL default '00-00-00 00:00:00',
  status enum('opened','closed') default 'opened',
template enum('stars', 'like') default 'stars',

  PRIMARY KEY  ( id),
key (idobject, typeobject),
  KEY votes (votes),
  KEY rate (rate)