  id int unsigned NOT NULL auto_increment,
  media enum('bin','image', 'audio','video', 'flash', 'document', 'executable','text','archive') default 'bin',
      mime enum ('application/octet-stream', 'image/jpeg', 'image/png', 'image/gif', 'image/bmp',
       'image/x-icon', 'image/tiff', 'image/vnd.wap.wbm', 'image/x-xbitmap', 'image/pict',
      'audio/mpeg', 'audio/mp44', 'audio/x-wav', 'audio/ogg',
      'video/mp4', 'video/mpeg', 'video/ogg', 'video/webm', 'video/x-flv',
'application/x-shockwave-flash',
      'text/plain'
      ) default 'application/octet-stream',

  parent int unsigned NOT NULL default '0',
  midle int unsigned NOT NULL default '0',
  preview int unsigned NOT NULL default '0',
  author int unsigned NOT NULL default '0',
idperm int unsigned NOT NULL default '0',
  width int unsigned NOT NULL default '0',
  height int unsigned NOT NULL default '0',
  size int unsigned NOT NULL default '0',
  posted datetime NOT NULL default '2010-01-01 10:01:01',
  hash char(22) NOT NULL,
  filename varchar(255) NOT NULL,
  title text  NOT NULL,
  description text  NOT NULL,
  keywords text  NOT NULL,

  PRIMARY KEY  (id),
  KEY parent (parent),
  KEY midle(midle),
  KEY preview (preview),
 KEY author (author),
  KEY media (media),
  KEY posted (posted)
