  id int unsigned NOT NULL auto_increment,
  idurl int unsigned NOT NULL default '0',
  parent int unsigned NOT NULL default '0',
  author int unsigned NOT NULL default '0',
  idperm int unsigned NOT NULL default '0',
  revision int unsigned NOT NULL default '0',
  icon int unsigned NOT NULL default '0',
  idview int unsigned NOT NULL default '1',
  class enum('litepubl-post-Post') default 'litepubl-post-Post',
  status enum('published','draft','future','deleted') default 'published',
  comstatus enum('closed','reg','guest','comuser') default 'comuser',
  pingenabled boolean default true,
  commentscount int unsigned NOT NULL default '0',
  pingbackscount int unsigned NOT NULL default '0',
  pagescount int unsigned NOT NULL default '0',
  posted datetime NOT NULL default '0000-00-00 00:00:00',
  rawhead text NOT NULL,
  title text NOT NULL,
  title2 text NOT NULL,
  filtered longtext NOT NULL,
  excerpt text NOT NULL,
  rss text NOT NULL,
  keywords text NOT NULL,
  description text NOT NULL,
  moretitle text NOT NULL,
  categories text NOT NULL,
  tags text NOT NULL,
  files text NOT NULL,
  password varchar(22) NOT NULL default '',

  PRIMARY KEY  (id),
  KEY posted (posted),
  KEY status (status)
